const dataSummary=[
    {
        id:1,
        profileName:'Liver Profile',
        tests:[
            {
                testName:'Albumin',
                result:2.88,
                unit:'g/dL',
                initialNormalRange:3.2,
                higherNormalRange:4.6,
                zone:'red'
            },
            {
                testName:'Albumin Albumin',
                result:2.88,
                unit:'g/dL',
                initialNormalRange:2.2,
                higherNormalRange:4.6,zone:'red'
            },
            {
                testName:'Albumin',
                result:2.88,
                unit:'g/dL',
                initialNormalRange:2.88,
                higherNormalRange:4.61,zone:'red'
            },
            {
                testName:'Albumin',
                result:2.88,
                unit:'g/dL',
                initialNormalRange:3.2,
                higherNormalRange:4.6,zone:'red'
            },
            {
                testName:'Albumin',
                result:2.88,
                unit:'g/dL',
                initialNormalRange:3.2,
                higherNormalRange:4.6,zone:'red'
            },
        ]
    },
    {
        id:2,
        profileName:'Liver Profile',
        tests:[
            {
                testName:'Albumin',
                result:2.88,
                unit:'g/dL',
                initialNormalRange:3.2,
                higherNormalRange:4.6,zone:'red'
            },
            {
                testName:'Albumin',
                result:2.88,
                unit:'g/dL',
                initialNormalRange:3.2,
                higherNormalRange:4.6,zone:'red'
            },
            {
                testName:'Albumin',
                result:2.88,
                unit:'g/dL',
                initialNormalRange:3.2,
                higherNormalRange:4.6,zone:'red'
            },
            {
                testName:'Albumin',
                result:2.88,
                unit:'g/dL',
                initialNormalRange:3.2,
                higherNormalRange:4.6,zone:'red'
            },
            {
                testName:'Albumin',
                result:2.88,
                unit:'g/dL',
                initialNormalRange:3.2,
                higherNormalRange:4.6,zone:'yellow'
            },
        ]
    }
]
export default dataSummary;